name: stream_skeleton
description: A basic architecture to handle your flutter project at ease.
version: 1.0.0
repository: https://github.com/xedeveloper/stream_skeleton

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  dart_code_metrics: ^5.7.5


flutter:
  uses-material-design: true